### ISSUE TITLE
cannot open bam file on big endian systems

### ISSUE THREAD

**Issue by domibel** [pezmaster31/bamtools#113]
With v2.4 it is not possible to open bam files on big endian systems:

A simple test case is
$ bamtools count -in test.bam
bamtools count ERROR: could not open input BAM file(s)... Aborting.

I tracked this back to the following function. 
https://github.com/pezmaster31/bamtools/blob/02c2be8866f9e43b1b5f0f80e4daae5ff352c06b/src/api/internal/io/BgzfStream_p.cpp
```
// checks BGZF block header
bool BgzfStream::CheckBlockHeader(char* header) {
    return (header[0] == Constants::GZIP_ID1 &&
            header[1] == Constants::GZIP_ID2 &&
            header[2] == Z_DEFLATED &&
            (header[3] & Constants::FLG_FEXTRA) != 0 &&
            BamTools::UnpackUnsignedShort(&header[10]) == Constants::BGZF_XLEN &&
            header[12] == Constants::BGZF_ID1 &&
            header[13] == Constants::BGZF_ID2 &&
            BamTools::UnpackUnsignedShort(&header[14]) == Constants::BGZF_LEN );
}
```

https://github.com/pezmaster31/bamtools/blob/02c2be8866f9e43b1b5f0f80e4daae5ff352c06b/src/api/BamAux.h
```
API_EXPORT inline unsigned short UnpackUnsignedShort(const char* buffer) {
    union { unsigned short value; unsigned char valueBuffer[sizeof(unsigned short)]; } un;
    un.value = 0;
    un.valueBuffer[0] = buffer[0];
    un.valueBuffer[1] = buffer[1];
    return un.value;
}
```

I can read the bam file after swapping the buffers on the big endian system
```
    un.valueBuffer[0] = buffer[1];
    un.valueBuffer[1] = buffer[0];
```

After reading BamAux.h it looks like bamtools has some kind of big endian support, but this case here is unhandled.

**Comment by domibel** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807979

**Comment by mr-c** [comment]
Here is the patch, by @domibel , that was applied to fix this in Debian

To view: http://sources.debian.net/patches/bamtools/2.4.0%2Bdfsg-3/0007-Big_Endian.patch/
To download: http://sources.debian.net/data/main/b/bamtools/2.4.0+dfsg-3/debian/patches/0007-Big_Endian.patch

**Comment by mr-c** [comment]
And a proper PR for the above https://github.com/pezmaster31/bamtools/pull/119

**Comment by pezmaster31** [comment]
Merged #119 a few days ago. Did that resolve this?

**Comment by domibel** [comment]
Yes, thank you!

**Comment by pezmaster31** [comment]
Thanks @mr-c
