### ISSUE TITLE
Lacks installation instructions

### ISSUE THREAD

**Issue by Jeltje** [pezmaster31/bamtools#114]
I downloaded the bamtools-2.4.0 release, untarred, and cd'd into the top directory.
I installed cmake and ran 
`cmake .`
but that died with 

```
CMake Error at CMakeLists.txt:20 (message):


    BamTools requires an out of source build.
    $ mkdir build
    $ cd build
    $ cmake ..
    $ make

 (or the Windows equivalent)

Call Stack (most recent call first):
  CMakeLists.txt:24 (ensure_out_of_source_build)

-- Configuring incomplete, errors occurred!
```

I know nothing about cmake, so an INSTALL file would be helpful.

**Comment by atsyganov** [comment]
if you follow the instructions here (https://github.com/pezmaster31/bamtools/wiki/Building-and-installing) you shodul be able to build it , there is no "install" file.

**Comment by SoapZA** [comment]
The instructions page on the wiki now has an installation section: https://github.com/pezmaster31/bamtools/wiki/Building-and-installing#install-bamtools
