### ISSUE TITLE
class Json::Reader’ has no member named ‘getFormattedErrorMessages’

### ISSUE THREAD

**Issue by grenaud** [pezmaster31/bamtools#127]
I get the following on ubuntu on a Intel Xeon with g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
:

[ 89%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_filter.cpp.o
bamtools/src/toolkit/bamtools_filter.cpp: In member function ‘bool BamTools::FilterTool::FilterToolPrivate::ParseScript()’:
bamtools/src/toolkit/bamtools_filter.cpp:650:25: error: ‘class Json::Reader’ has no member named ‘getFormattedErrorMessages’
               << reader.getFormattedErrorMessages();

**Comment by pezmaster31** [comment]
Reverted that PR.

**Comment by grenaud** [comment]
seems to have fixed it, thank you very much.
