### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by davidmatten** [pezmaster31/bamtools#131]
Same as others - when trying to compile I get the following error:

[ 98%] Building CXX object src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_split.cpp.o
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In member function ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&)’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:517:39: error: ‘WriterMap’ has no member named ‘cend’
         if (writerIter == outputFiles.cend()) {
                                       ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = signed char]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:415:95:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = short int]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:416:96:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = int]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:417:96:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = unsigned char]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:418:96:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = short unsigned int]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:419:97:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = unsigned int]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:420:97:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp: In instantiation of ‘bool BamTools::SplitTool::SplitToolPrivate::SplitListTagImpl(BamTools::BamAlignment&) [with T = float]’:
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:421:94:   required from here
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:504:86: error: ‘TagValueType’ has no member named ‘cbegin’
             typename TagValueType::const_iterator tagValueIter = currentValue.cbegin();
                                                                                      ^
/home/dave/Software/bamtools/src/toolkit/bamtools_split.cpp:505:84: error: ‘TagValueType’ has no member named ‘cend’
             typename TagValueType::const_iterator tagValueEnd  = currentValue.cend();
                                                                                    ^
make[2]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_split.cpp.o] Error 1
make[1]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make: *** [all] Error 2

**Comment by datakid** [comment]
Confirm this as well. 

I did this with: the git checkout for "2.4.1" (51ba207654e4d298321163976bcbbbfdc3e27788), Centos 7, cmake 2.8.11, make 3.8.2

**Comment by SignMyPublicKey** [comment]
Confirm this compile error as well.
Mine was with:
- Latest commit 8df1a3e
- Ubuntu 14.04 LTS
- cmake 2.8.12.2
- make 3.81

**Comment by robertopreste** [comment]
Same error, with Make 3.81 and cmake 3.5.2.
Any fix available?

**Comment by pezmaster31** [comment]
Going to close this since #132 should fix it. Feel free to reopen if not.

**Comment by SignMyPublicKey** [comment]
Fixed it for me, thanks!

**Comment by davidmatten** [comment]
Fixed it for me, thanks!

**Comment by datakid** [comment]
Addendum:

- gcc version 4.8.5
- Also didn't work for master, same error
- neither worked when I tried to do it in /tmp instead of a mounted filesystem
- *did* work when I checked out 2.4.0 (71392a251aaea8b797661846b2878e16efd04285)
- worked on the mounted filesystem (didn't need to move to /tmp)

**Comment by datakid** [comment]
I checked out cbca090607f2154aa19c20ca778c3d067384b606 and it worked a treat. Thanks!
