### ISSUE TITLE
Problems compiling with Visual Studio

### ISSUE THREAD

**Issue by lamortenera** [pezmaster31/bamtools#134]
Hi, 
I followed the intallation instructions to compile BamTools on Windows using Visual Studio, I have version 2015. I downloaded cmake for windows 64 bits, created the build subdirectory, and ran cmake. All fine till there.

I then opened the solution with visual studio and tried to build the whole solution.
First attempt, visual studio fails because of the following error:

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(17): error C2371: 'int8_t': redefinition; different basic types
>  C:\Users\amammana\Desktop\test_bamtools\bamtools-2.4.0\src\shared/bamtools_global.h(65): note: see declaration of 'int8_t'

So I tried to modify line 65 of bamtools_globals.h from:

typedef  char int8_t;

into

typedef signed char int8_t;

This seemed to get me a bit further. It seems like I succeeded to compile the subproject bamtools-static, which provides the .lib file and was the main thing I was aiming for.  
However, trying to compile the other projects, I get many different errors. One of the most frequent is:

> LINK : fatal error LNK1104: cannot open file 'z.lib'
> which I think it's related to 'ftello',  'fseeko', ... not found

Does that mean that I need to find a suitable z.lib ? How can Bamtools-static work without z.lib ?

Then I also get errors like:

> C:\path\bamtools-2.4.0\src\utils/bamtools_filter_engine.h(186): error C2491: 'BamTools::FilterEngine<FilterChecker>::addFilter': definition of dllimport function not allowed
> 
> C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(221): error C2039: 'greater': is not a member of 'std'
>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sstream(12): note: see declaration of 'std'
> C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(221): error C2065: 'greater': undeclared identifier
> C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(221): error C2275: 'ModelType': illegal use of this type as an expression
>  C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(98): note: see declaration of 'ModelType'
> C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(221): error C2059: syntax error: ')'
> C:\path\bamtools-2.4.0\src\toolkit\bamtools_resolve.cpp(610): error C2664: 'std::pairstd::basic_string<char,std::char_traits<char,std::allocator<char>>,ReadGroupResolver> std::make_pairstd::string,ReadGroupResolver(_Ty1 &&,_Ty2 &&)': cannot convert argument 1 from 'const std::string' to 'std::string &&'

This prevents the subproject bamtools_cmd from being compiled.

Could you help me out with that? I am happy to provide more detail

As a curiosity, why is there a project callled jsoncpp? what does BAM have to do with json?

Thanks in advance,
Alessandro Mamana

**Comment by lamortenera** [comment]
Unfortunately I am not able to use the compiled library. When I try to use libbamtools.lib to compile a toy project, the linker complains about things that it cannot find.

At first I got the following errors:

>libbamtools.lib(BamReader_p.obj) : error LNK2001: unresolved external symbol "public: enum BamTools::Internal::BamRandomAccessController::RegionState __thiscall BamTools::Internal::BamRandomAccessController::AlignmentState(struct BamTools::BamAlignment const &)const " (?AlignmentState@BamRandomAccessController@Internal@BamTools@@QBE?AW4RegionState@123@ABUBamAlignment@3@@Z)
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _deflate
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _deflateEnd
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _inflate
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _inflateEnd
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _crc32
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _deflateInit2_
>libbamtools.lib(BgzfStream_p.obj) : error LNK2001: unresolved external symbol _inflateInit2_


I guessed that most of these errors were coming from a missing zlib. So I downloaded zdll.lib from http://zlib.net/zlib128-dll.zip and I added it to the linker dependencies. 

After doing that, one error remains:


>libbamtools.lib(BamReader_p.obj) : error LNK2001: unresolved external symbol "public: enum BamTools::Internal::BamRandomAccessController::RegionState __thiscall BamTools::Internal::BamRandomAccessController::AlignmentState(struct BamTools::BamAlignment const &)const " (?AlignmentState@BamRandomAccessController@Internal@BamTools@@QBE?AW4RegionState@123@ABUBamAlignment@3@@Z)


Could you help me out with that?
If downloading zdll.lib is indeed necessary to use a statically compiled version of bamtools, could you please mention it somewhere ? it would save a lot of time to people like me.

**Comment by mhettich12** [comment]
Did you ever get this resolved? I went through the exact steps and errors as you did. Any luck getting your project to compile?

**Comment by lamortenera** [comment]
no, no luck unfortunately :-(

**Comment by SoapZA** [comment]
Please try with latest `HEAD`, which has a number of fixes for Windows.
