### ISSUE TITLE
Implicit change of EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH

### ISSUE THREAD

**Issue by miepstei** [pezmaster31/bamtools#164]
Apologies for the lack of title; mistakenly pressed return.

I am building bamtools as per the documentation:
`mkdir build && cd build`
`cmake ..`
`make`
`cd ..`

and the output is built under `src/api` ... not `lib` or `bin` as specified in the documentation. Is this a recent change?

I know I could copy the libraries I need but my use case is part of an automated build process.

**Comment by dwinter** [comment]
+1, this is breaking my build at the moment, so confirmation that this is a permanent change would be appreciated.

**Comment by SoapZA** [comment]
I am aware of this, and it was done on purpose and I will not budge on this issue. In general, the structure of the build tree is an implementation detail of the build system being used and people tend to rely on implementation details that they should never relied upon. You should **never** copy stuff out of the build tree. Instead, you should always **install** or **stage** your build by doing

```
cmake -DCMAKE_INSTALL_PREFIX=/my/install/dir ..
make
make DESTDIR=/my/stage/dir install
```

after which the root of the installed files will be `/my/stage/dir/my/install/dir`. `DESTDIR` can be omitted if you know the final persistent dir you want to install bamtools to. There are good reasons for preferring this route. What if we need to add a temporary `RPATH` for testing? Only upon running `make install` is the `RPATH` removed again, by performing an additional relinking step. If you copy stuff out of the build dir, you might be copying a binary with an `RPATH` set, which is a potential security vulnerability.

Additionally, the build system uses the `GNUInstallDirs` module, meaning you can further configure the binary, lib and include dirs using `CMAKE_INSTALL_BINDIR`, `CMAKE_INSTALL_LIBDIR` and `CMAKE_INSTALL_INCLUDEDIR`.

Nonetheless, I will update the docs to reflect this proper building and installation paradigm.

**Comment by SoapZA** [comment]
Updated https://github.com/pezmaster31/bamtools/wiki/Building-and-installing with the updated, modern CMake best practices.

**Comment by miepstei** [comment]
I have no disagreement with the route you have gone down - I was building a third party tool whose source I cannot change. It was more the fact that the documentation at the time did not reflect this updated build process and CMake variables you have since highlighted. Thanks for updating for documentation.
