### ISSUE TITLE
BgzfStream_p.cpp:(.text+0x1da): undefined reference to

### ISSUE THREAD

**Issue by datakid** [pezmaster31/bamtools#174]
While compiling another tool ([origami](https://github.com/younglab/origami)), I am getting these "undefined reference to" errors. 

Any tips on how to over come this? I have zlib and zlib-devel installed. CentOS 7.4, cpp/gcc 4.8.5 

```
[root@server origami-1.1]# make
cd src && g++ -I/binaries/bamtools/2.5.0/include/bamtools/ -c mapped-reads-merge.cpp
cd src && g++ -o mapped-reads-merge mapped-reads-merge.o -lbamtools
/binaries/bamtools/2.5.0/lib64/../lib64/libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::InflateBlock(unsigned long const&)':
BgzfStream_p.cpp:(.text+0x1da): undefined reference to `inflateInit2_'
BgzfStream_p.cpp:(.text+0x1ed): undefined reference to `inflate'
BgzfStream_p.cpp:(.text+0x200): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0x2a7): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0x2f5): undefined reference to `inflateEnd'
/binaries/bamtools/2.5.0/lib64/../lib64/libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::DeflateBlock(int)':
BgzfStream_p.cpp:(.text+0xc01): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0xc7b): undefined reference to `deflateInit2_'
BgzfStream_p.cpp:(.text+0xc92): undefined reference to `deflate'
BgzfStream_p.cpp:(.text+0xca8): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0xce4): undefined reference to `crc32'
BgzfStream_p.cpp:(.text+0xcf1): undefined reference to `crc32'
collect2: error: ld returned 1 exit status
```

**Comment by datakid** [comment]
I haven't checked properly, but I presume the errors are a direct result of [this commit](https://github.com/pezmaster31/bamtools/commit/dcf1358f0f4963cd19c11dff516ae286e00b8e12)?

I have zlib.h on my system, it's in /usr/include/ and it's version 1.2.7, so sufficiently current. In it I see the crc32 and other missing references. 

When I run `cmake3  -DCMAKE_INSTALL_PREFIX=/binaries/bamtools/2.5.0 ..` I see that libz.so is found `-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")`

**Comment by SoapZA** [comment]
This is a general problem of static libraries: static libraries, unlike dynamic ones, do not carry any information about dependencies with them. We offer pkg-config files, unfortunately those do not contain the zlib dependency. I have pushed a fix for this in 9e09e28

You have 2 ways to approach this issue:
1. Use shared libraries (specify `-DBUILD_SHARED_LIBS=ON` to CMake). This avoids the issue, as shared libraries know their dependencies. You might have to fiddle with `RPATH` and/or `LD_LIBRARY_PATH`.
2. Use pkg-config. This is the preferred solution, as it scales better and is less brittle. Unfortunately, pkg-config files cannot introspect the installed libraries, which means you will have to specify `--static` to pkg-config if you are using a static library of bamtools:

```
$ pkg-config --libs bamtools-1
-L/usr/local/lib -lbamtools
$ pkg-config --libs --static bamtools-1
-L/usr/local/lib -L/opt/local/lib -lbamtools -lz -ljsoncpp
```

**Comment by datakid** [comment]
Thanks. I applied your patch to 2.5.0, used the -DBUILD_SHARED_LIBS=ON and had to set the LIBRARY_PATH to point to the bamtools library. Second option is attractive but installing on a shared HPC system using environment modules rather than general install into /usr/local. Worked a treat. Thank you.

**Comment by BJWiley233** [comment]
-DBUILD_SHARED_LIBS=ON works with Ubuntu docker!
