### ISSUE TITLE
Can't get bamtools  ## ERROR 404: Not Found

### ISSUE THREAD

**Issue by ashaneev** [pezmaster31/bamtools#176]
home@home-Lenovo-H30-50:~/Documents/Annotation_tools/augustus$ wget https://github.com/pezmaster31/bamtools.wiki.git
--2018-03-14 15:33:14--  https://github.com/pezmaster31/bamtools.wiki.git
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/pezmaster31/bamtools.wiki [following]
--2018-03-14 15:33:20--  https://github.com/pezmaster31/bamtools.wiki
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2018-03-14 15:33:21 ERROR 404: Not Found.

**Comment by SoapZA** [comment]
this is a git repo, you have to `git clone` it
