### ISSUE TITLE
fail to compile bamtools in windows system

### ISSUE THREAD

**Issue by xiaowenchenjax** [pezmaster31/bamtools#179]
Hi 
i tried to build bamtools in 64bit window system using nmake in visual studio.  but it failed. Could you help me to fix it?
please see the attach file for the error. 
Thank you very much.
[bamtools_windows.log](https://github.com/pezmaster31/bamtools/files/2149808/bamtools_windows.log)

**Comment by SoapZA** [comment]
Please try with latest `HEAD`, which has a number of fixes for Windows.
