### ISSUE TITLE
trying to link on conda

### ISSUE THREAD

**Issue by grenaud** [pezmaster31/bamtools#180]
Using conda I ran:

`conda config --add channels defaults`
`conda config --add channels conda-forge`
`conda config --add channels bioconda`
`conda install bamtools`

this is all fine, I can compile but not link:
undefined reference to BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&, unsigned int const&, unsigned int&) const'

It seems that there is a discrepancy between the names in the libbamtools.a file and in the one I compile:

`nm -A ReconsReferenceBAM.o  |grep -i findtag
ReconsReferenceBAM.o:
                      U
_ZNK8BamTools12BamAlignment7FindTagERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERPcRKjRj`

But this symbol is there:

`nm -A /home/gabriel/.conda/envs/test_gabriel/lib/libbamtools.a |grep -i findtag
/home/gabriel/.conda/envs/test_gabriel/lib/libbamtools.a:BamAlignment.cpp.o:00000000000012d0
T _ZNK8BamTools12BamAlignment7FindTagERKSsRPcRKjRj`

Notice the missing basic_stringIcSt11char
However, if I compile the program using my local build, it links
without any problem because the symbol has the basic_stringIcSt11char:

`nm -A /tmp/bamtools/build/src/api//libbamtools.a  |grep -i findtag
/tmp/bamtools/build/src/api//libbamtools.a:BamAlignment.cpp.o:0000000000001690
              T
_ZNK8BamTools12BamAlignment7FindTagERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERPcRKjRj`

**Comment by SoapZA** [comment]
`undefined reference to BamTools::BamAlignment::FindTag(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, char*&, unsigned int const&, unsigned int&) const'`

That is related to the GCC 5 ABI switch, your compilers and paths are munged.
