### ISSUE TITLE
Cannot build on windows (mingw32)

### ISSUE THREAD

**Issue by mszhanghm** [pezmaster31/bamtools#181]
I tried to build on mingw (installed the latest release at https://sourceforge.net/projects/mingw/files/latest/download), and failed. Here is the detail.

The step for creating makefile by cmake worked without glitch (in the dir /build):
>cmake -G"MinGW Makefiles" -D CMAKE_CXX_COMPILER="C:/MinGW/bin/g++.exe" -D CMAKE_SH="CMAKE_SH-NOTFOUND" ..

-- The CXX compiler identification is GNU 6.3.0
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/MinGW/bin/pkg-config.exe (found version "0.26") 
-- Checking for one of the modules 'jsoncpp>=1'
-- Found ZLIB: C:/ProgramData/Anaconda3/Library/lib/z.lib (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/zhangm/git_repos/bamtools/build

Then the build step failed-
> C:/MinGW/bin/mingw32-make.exe

Scanning dependencies of target SharedHeaders
[  0%] Built target SharedHeaders
Scanning dependencies of target BamTools
[  1%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.obj
[  3%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.obj
[  4%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamReader.cpp.obj
[  6%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.obj
[  8%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.obj
[  9%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.obj
[ 11%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.obj
[ 13%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.obj
[ 14%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.obj
[ 16%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.obj
[ 18%] Building CXX object src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.obj
[ 19%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.obj
[ 21%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.obj
[ 22%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.obj
[ 24%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.obj
[ 26%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.obj
[ 27%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.obj
[ 29%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.obj
[ 31%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.obj
[ 32%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.obj
[ 34%] Building CXX object src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.obj
In file included from C:/Users/zhangm/git_repos/bamtools/src/api/api_global.h:13:0,
                 from C:/Users/zhangm/git_repos/bamtools/src/api/IBamIODevice.h:23,
                 from C:/Users/zhangm/git_repos/bamtools/src/api/internal/io/ILocalIODevice_p.h:23,
                 from C:/Users/zhangm/git_repos/bamtools/src/api/internal/io/BamFile_p.h:24,
                 from C:\Users\zhangm\git_repos\bamtools\src\api\internal\io\BamFile_p.cpp:10:
C:\Users\zhangm\git_repos\bamtools\src\api\internal\io\BamFile_p.cpp: In member function 'virtual bool BamTools::Internal::BamFile::Seek(const int64_t&, int)':
C:/Users/zhangm/git_repos/bamtools/src/shared/bamtools_global.h:43:43: error: '_fseeki64' was not declared in this scope
 #define fseek64(a, b, c) _fseeki64(a, b, c)
                                           ^
C:\Users\zhangm\git_repos\bamtools\src\api\internal\io\BamFile_p.cpp:72:13: note: in expansion of macro 'fseek64'
     return (fseek64(m_stream, position, origin) == 0);
             ^~~~~~~
src\api\CMakeFiles\BamTools.dir\build.make:342: recipe for target 'src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.obj' failed
mingw32-make.exe[3]: *** [src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.obj] Error 1
CMakeFiles\Makefile2:156: recipe for target 'src/api/CMakeFiles/BamTools.dir/all' failed
mingw32-make.exe[2]: *** [src/api/CMakeFiles/BamTools.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make.exe[1]: *** [all] Error 2

I tried to build on Visual Studio 2017, and it failed as well (I will create a separate issue for that). So it seemed not like a mingw specific issue

**Comment by SoapZA** [comment]
Please try with latest `HEAD`, which has a number of fixes for Windows.
