### ISSUE TITLE
cannot build on windows (visual studio 2017)

### ISSUE THREAD

**Issue by mszhanghm** [pezmaster31/bamtools#182]
Tried to build in visual studio 2017, and failed. Here are details-

Output from CMake (worked OK):
Switching to configuration x64-Release.... 
1> Command line: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\zhangm\CMakeBuilds\388f00b3-512f-9432-b437-6405447a5d4e\install\x64-Release"  -DCMAKE_CXX_COMPILER="C:/Program Files/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\zhangm\git_repos\bamtools"
1> Working directory: C:\Users\zhangm\CMakeBuilds\388f00b3-512f-9432-b437-6405447a5d4e\build\x64-Release
1> CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
1>   The OLD behavior for policy CMP0042 will be removed from a future version
1>   of CMake.
1> 
1>   The cmake-policies(7) manual explains that the OLD behaviors of all
1>   policies are deprecated and that a policy should be set to OLD only under
1>   specific short-term circumstances.  Projects should be ported to the NEW
1>   behavior and not rely on setting a policy to OLD.
1> 
1> 
1> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
1> -- Checking for one of the modules 'jsoncpp>=1'
1> Did NOT find system JsonCpp, instead using bundled version
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: C:/Users/zhangm/CMakeBuilds/388f00b3-512f-9432-b437-6405447a5d4e/build/x64-Release
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Target info extraction done.
Configuration switch to x64-Release complete.

The build process exited with 1154 warnings, and 9 errors. Here are some of the errors-

Code	Severity	Description	Project	File	Line	Suppression State
C2491	Error	'BamTools::FilterEngine<FilterChecker>::buildRuleQueue': definition of dllimport function not allowed	C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\zhangm\git_repos\bamtools\src\utils\bamtools_filter_engine.h	266	
C2491	Error	'BamTools::FilterEngine<FilterChecker>::enabledPropertyNames': definition of dllimport function not allowed	C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\zhangm\git_repos\bamtools\src\utils\bamtools_filter_engine.h	292	
C2491	Error	'BamTools::FilterEngine<FilterChecker>::filterNames': definition of dllimport function not allowed	C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\zhangm\git_repos\bamtools\src\utils\bamtools_filter_engine.h	370	
C2491	Error	'BamTools::FilterEngine<FilterChecker>::setDefaultCompareType': definition of dllimport function not allowed	C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\zhangm\git_repos\bamtools\src\utils\bamtools_filter_engine.h	505	
C2491	Error	'BamTools::FilterEngine<FilterChecker>::setRule': definition of dllimport function not allowed	C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CMakeLists.txt	C:\Users\zhangm\git_repos\bamtools\src\utils\bamtools_filter_engine.h	571

**Comment by SoapZA** [comment]
Please try with latest `HEAD`, which has a number of fixes for Windows.
