### ISSUE TITLE
problem compiling bamtools with CMAKE  3.1.4 on Mac OS 10.13.6 (sierra)

### ISSUE THREAD

**Issue by wsossin** [pezmaster31/bamtools#186]
Sorry, if this seems naive, but I am just getting into bioinformatics.

I downloaded Cmake which now comes as an application. I download bamtools and put it in a folder in applications. I use Cmake to configure (configure again because there are red variables) and generate (in a build folder in the bamtools-master folder). I then (on Monitor) go to the build directory and use make. Below is the error message. What am I doing wrong??

Scanning dependencies of target SharedHeaders
[  0%] Built target SharedHeaders
Scanning dependencies of target APIHeaders
[  0%] Built target APIHeaders
Scanning dependencies of target AlgorithmsHeaders
[  0%] Built target AlgorithmsHeaders
Scanning dependencies of target BamTools
[  1%] Building CXX object api/CMakeFiles/BamTools.dir/BamAlignment.o
/Applications/bamtools-master/src/api/BamAlignment.cpp:10:10: fatal error: 
      'api/BamAlignment.h' file not found
#include "api/BamAlignment.h"

1 error generated.
make[2]: *** [api/CMakeFiles/BamTools.dir/BamAlignment.o] Error 1
make[1]: *** [api/CMakeFiles/BamTools.dir/all] Error 2
make: *** [all] Error 2

**Comment by SoapZA** [comment]
CMake bug? building on macOS works fine here.
