### ISSUE TITLE
Guide to installing bamtools

### ISSUE THREAD

**Issue by emmannaemeka** [pezmaster31/bamtools#197]
I have been having hard times installing bamtools

what I have tried so far
cd bamtools
mkdir build
cmake3 /home/emmanuel/bamtools-2.4.2/CMakeLists.txt

error
CMake Deprecation Warning at CMakeLists.txt:20 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Error at CMakeLists.txt:40 (message):
  

    BamTools requires an out of source build.
    $ mkdir build
    $ cd build
    $ cmake ..
    $ make

  (or the Windows equivalent)

Call Stack (most recent call first):
  CMakeLists.txt:44 (ensure_out_of_source_build)

-- Configuring incomplete, errors occurred!

**Comment by Rhinogradentia** [comment]
Hi,
I have the same problem  - is there any chance you solved this?
best

**Comment by emmannaemeka** [comment]
Hi,
I rather used conda install -c bioconda bamtools
conda install -c bioconda/label/cf201901 bamtools


Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by carolynzy** [comment]
I once encountered this error because I have run cmake before, and there is CMakeCache.txt in the source directory. After I deleted the file it went on well.
