### ISSUE TITLE
any release soon? use 2.5.1 or master?

### ISSUE THREAD

**Issue by santiagorevale** [pezmaster31/bamtools#199]
Hi @pezmaster31,

I was wondering if you are planning on making a new release soon. Last release is from 2017 and I've noticed that latest commits are from Sep 2019.

If no plans for new releases, is it safe to use "master" or should I still use 2.5.1?

Thanks in advance.

Cheers,
Santiago

**Comment by Stikus** [comment]
Any news? Latest commits are from May 2020 but release is from 2017.

**Comment by serge2016** [comment]
Same question!

**Comment by SoapZA** [comment]
I'll prepare a release soon, I'd just like to get a few more fixes in

**Comment by SoapZA** [comment]
2.5.2 has just been released.
