### ISSUE TITLE
bamtools installation error

### ISSUE THREAD

**Issue by jiangshan529** [pezmaster31/bamtools#207]
CMake Error at CMakeLists.txt:37 (message):
  

    BamTools requires an out of source build.
    $ mkdir build
    $ cd build
    $ cmake ..
    $ make

  (or the Windows equivalent)

Call Stack (most recent call first):
  CMakeLists.txt:41 (ensure_out_of_source_build)

-- Configuring incomplete, errors occurred!
See also "/home/biosoft/bamtools/CMakeFiles/CMakeOutput.log".

I have mkdir build. how to deal with this? Thanks!

**Comment by jiangshan529** [comment]
I mean I have done all the steps "mkdir build, cd build, cmake ..", the error reports in "cmake" step, I have cmake version of 3.2.0.

**Comment by SoapZA** [comment]
if `mkdir build && cd build && cmake .. && make` doesn't work for you, then you might have to checkout a few CMake tutorials.
