### ISSUE TITLE
install_error_cmake

### ISSUE THREAD

**Issue by rhnonaka** [pezmaster31/bamtools#216]
Hi,

I've been trying to install Bamtools, but I got this error when I run cmake command:

## Found system JsonCpp, not using bundled version
CMake Error at /usr/local/share/cmake-3.2/Modules/GenerateExportHeader.cmake:312 (message):
  Unknown keywords given to GENERATE_EXPORT_HEADER():
  "INCLUDE_GUARD_NAME;BAMTOOLS_API_EXPORT_H"##

OS: Ubuntu 16.04 and 18.04
Cmake: 3.2, 3.5.1, 3.9.1 , 3.10.2

I will appreciated  any help.

Best Regards,

Ricardo

**Comment by SoapZA** [comment]
yup, you will need CMake 3.11 at a minimum, I will bump the requirement
