### ISSUE TITLE
git clone not working

### ISSUE THREAD

**Issue by matosmr** [pezmaster31/bamtools#227]
Hi, there seems to be a broken pipe here. I've been trying to clone this repository and I keep getting an error. I tried cloning another git repository and it worked with no problem, so I know the issue seems not to be from my end.

 git clone git://github.com/pezmaster31/bamtools.git
Cloning into 'bamtools'...
fatal: unable to connect to github.com:

**Comment by SoapZA** [comment]
Github infra issue, report it to them directly.
