### ISSUE TITLE
BamAlignment::RefID broken

### ISSUE THREAD

**Issue by davidhanna** [pezmaster31/bamtools#34]
Hi all,

It looks like the RefID integer in the BamAlignment class is always populated as = 0 by the BamReader GetNextAlignment function.  This makes it pretty hard to use to the Jump function in BamReader.  I'll try to track down why this output is given, but thought it would be good to confirm others have the same issue.

Thanks,
DSH

**Comment by yazhinia** [comment]
Hello,
       I have reference ids named S0C0, S0C1, S0C3, etc in string type. When I read .bam alignment file using `while ( reader.GetNextAlignment(al) )`, I observe that al.RefID becomes 0, 1, 2, 3, etc (int32_t type). Is there a way to keep al.RefID as a string with `S0C` tag intact?
