### ISSUE TITLE
bamtools: command not found

### ISSUE THREAD

**Issue by bs98scd** [pezmaster31/bamtools#49]
Hi,
Apologies, as I'm a bit of a novice with anything linux related, but I have installed bamtools and can see the 'bamtools' in my bin and 'libbamtools...' in my lib directories, but when I try and run bamtools I get the message
bamtools: command not found
I'm not sure what I'm missing, any suggestions would be gratefully received!

**Comment by SoapZA** [comment]
This is clearly a `PATH` issue.
