### ISSUE TITLE
Add generated files to .gitignore.

### ISSUE THREAD

**Issue by nieder** [pezmaster31/bamtools#78]
This adds generated files to .gitignore. With this file, the number of unignored but untracked files in my compiled git directory drop from 265 to 22.

Includes both compiled files (.o, .so, etc) and CMake related files.  Entries were taken from https://github.com/github/gitignore.

There are several header files that I am not sure if they were generated or are left from a previous build, so I did not add them.

``` patch
From c462f086571c469967489045b7be3825554e6921 Mon Sep 17 00:00:00 2001
From: Hanspeter Niederstrasser <nieder@users.sourceforge.net>
Date: Wed, 3 Jul 2013 11:37:25 -0400
Subject: [PATCH] add .gitignore file

---
 .gitignore | 14 ++++++++++++++
 1 file changed, 14 insertions(+)
 create mode 100644 .gitignore

diff --git a/.gitignore b/.gitignore
new file mode 100644
index 0000000..f5bbf8f
--- /dev/null
+++ b/.gitignore
@@ -0,0 +1,14 @@
+*.a
+*.dylib
+*.o
+*.so
+*.so.*
+
+# Cmake generated files
+CMakeCache.txt
+CMakeFiles
+Makefile
+cmake_install.cmake
+install_manifest.txt
+link.txt
+
-- 
1.7.12.4 (Apple Git-37)

```

**Comment by SoapZA** [comment]
Add `build/` dir to `.gitignore` in https://github.com/pezmaster31/bamtools/commit/4d4c0c3f01bfc3cfa4e07e0afc732bed6be7579b.
