### ISSUE TITLE
cmake in the most recent version give errors

### ISSUE THREAD

**Issue by kemin711** [pezmaster31/bamtools#80]
I am not an expert in cmake, but here is the error message:

zhouke@europa[~/src/bamtools]$ mkdir build
zhouke@europa[~/src/bamtools]$ cd build
zhouke@europa[~/src/bamtools/build]$ cmake ..
CMake Error at CMakeLists.txt:20 (message):
  

    BamTools requires an out of source build.
    $ mkdir build 
    $ cd build
    $ cmake ..
    $ make 

  (or the Windows equivalent)

Call Stack (most recent call first):
  CMakeLists.txt:24 (ensure_out_of_source_build)

-- Configuring incomplete, errors occurred!

**Comment by DarioS** [comment]
I have the same problem and the solutions proposed don't work.

    /verona/nobackup/biostat/software/bamtools-master/B$ cmake ..
    CMake Error: Could not open file for write in copy operation /src/toolkit/bamtools_version.h.tmp
    CMake Error: : System Error: No such file or directory
    CMake Error at toolkit/CMakeLists.txt:38 (configure_file):
      configure_file Problem configuring file

Could the install process be made more robust ? Is it a requirement to use git clone ? I simply clicked the Download ZIP button, and unzipped the archive.

    /verona/nobackup/biostat/software/bamtools-master$ cat /etc/debian_version
    7.8

**Comment by plijnzaad** [comment]
This still doesn't work, I keep getting `Could not open file for write in copy operation /src/...`.
This is on a virgin git clone, using cmake 2.8.12.2 on CentOS 6.6:

<verbatim>
$ git clone https://github.com/pezmaster31/bamtools.git
Initialized empty Git repository in ~/src/bamtools/.git/
remote: Counting objects: 4059, done.
remote: Total 4059 (delta 0), reused 0 (delta 0), pack-reused 4059
Receiving objects: 100% (4059/4059), 2.77 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (2527/2527), done.
$ cd bamtools/
$ git show
commit 02c2be8866f9e43b1b5f0f80e4daae5ff352c06b
Merge: 71392a2 df972a0
Author: Derek Barnett <derekwbarnett@gmail.com>
Date:   Wed Jun 17 23:07:16 2015 -0400

    Merge pull request #105 from mjhsieh/patch-1
    
    one extra unicode string in the beginning of file
$ cd src/
$ mkdir build
$ cd build
$ cmake ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error: Could not open file for write in copy operation /src/toolkit/bamtools_version.h.tmp
CMake Error: : System Error: No such file or directory
CMake Error at toolkit/CMakeLists.txt:38 (configure_file):
  configure_file Problem configuring file


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "~/src/bamtools/src/build/CMakeFiles/CMakeOutput.log".
</verbatim>

**Comment by mibiledna** [comment]
To my experince, you should use the command "cmake ..bamtools/" please remember, do not use "cmake ..bamtools/src". That is, NO scr sub-directory is needed. Then, everything is going good!

**Comment by deveale** [comment]
I'm hoping to build bamtools with cmake version 3.3.1 on centos-release-6-7.el6.centos.12.3.x86_64  but received the error message below. 

'CMake Error at CMakeLists.txt:40 (message):
....
CMakeLists.txt:44 (ensure_out_of_source_build)' 

I've tried placing the build folder at the same level as the bamtools clone but received the same error. I tried replacing the text in the CMakeLists.txt file with 

"if( ${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_BINARY_DIR} )
    message( FATAL_ERROR "Out of source check failed." )
endif()"

but ended up with the same issue. 

cmake -DCMAKE_INSTALL_PREFIX=../bamtools
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: ../miniconda3/bin/cc
-- Check for working C compiler: ../miniconda3/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: ../miniconda3/bin/c++
-- Check for working CXX compiler: ../miniconda3/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:32 (message):
  Out of source check failed.

-- Configuring incomplete, errors occurred!
See also "/home/devealeb/bamtools/build/CMakeFiles/CMakeOutput.log".

Any advice on how to resolve this would be sincerely appreciated. Thanks, Brian

**Comment by codeprimate123** [comment]
For those having this issue, i tried the solution above placing build folder at the same level as the bamtools clone but kept getting the same error UNTIL I also deleted CMakeCache.txt from the bamtools clone folder. After deleting CMakeCache.txt i could build and install bamtools.

**Comment by zkidiavai** [comment]
Thanks. Deleting the CMakeCache.txt has just worked for me
